'use strict';

/**
 * Hebrew medical-terminology glossary for CRPS research surfacing.
 * Source: docs/research/01a-analyst-findings-crps.md §6.5.
 *
 * Used by 4d's reply formatter to ensure consistent Hebrew terminology
 * across summaries (e.g., "spinal cord stimulation" always becomes
 * "גירוי חוט שדרה", never an inconsistent paraphrase).
 *
 * Replacement is case-insensitive, longest-phrase-first to avoid
 * partial-overlap (e.g., "complex regional pain syndrome" must be tried
 * before bare "chronic pain"), and word-boundary anchored on Latin to
 * avoid "remission" inside another word.
 */

// Order is regenerated by length at module load — source order is for readability.
const GLOSSARY = {
  'CRPS':                              'CRPS',
  'complex regional pain syndrome':    'תסמונת כאב אזורי מורכב',
  'chronic pain':                      'כאב כרוני',
  'nerve block':                       'חסם עצב',
  'spinal cord stimulation':           'גירוי חוט שדרה',
  'DRG stimulation':                   'גירוי DRG',
  'remission':                         'הקלה משמעותית',
};

function escapeRegex(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// Pre-build replacement table once: longest first.
const REPLACEMENTS = Object.entries(GLOSSARY)
  .sort((a, b) => b[0].length - a[0].length)
  .map(([en, he]) => ({
    en,
    he,
    re: new RegExp(`\\b${escapeRegex(en)}\\b`, 'gi'),
  }));

function translateMedicalTerms(text) {
  if (text == null) return text;
  let out = String(text);
  for (const { re, he } of REPLACEMENTS) {
    out = out.replace(re, he);
  }
  return out;
}

module.exports = { translateMedicalTerms, GLOSSARY };
